name: "Add Badge to README"
description: "Afegix un badge al README, depenent del resultat dels tests de Cypress."
inputs:
  cypress_outcome:
    description: "Resultat (success o failure)"
    required: true
runs:
  using: "composite"
  steps:
    - run: ./index.sh
      shell: bash
      with:
        args: ${{ inputs.cypress_outcome }}
