name: nodejs-blog-practica-main_workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linter_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

  cypress_job:
    runs-on: ubuntu-latest
    needs: linter_job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Cypress tests and save output
        run: npm run cypress > result.txt || true # True fa que es guarde encara que falle.

      - name: Upload result.txt
        uses: actions/upload-artifact@v3
        with:
          name: result.txt
          path: result.txt
