name: nodejs-blog-practica-main_workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linter_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

  cypress_job:
    runs-on: ubuntu-latest
    needs: linter_job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Cypress tests and save output
        run: npm run cypress > result.txt || true # True fa que es guarde encara que falle.

      - name: Upload result.txt
        uses: actions/upload-artifact@v3
        with:
          name: result.txt
          path: result.txt

  add_badge_job:
    runs-on: ubuntu-latest
    needs: cypress_job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download result.txt
        uses: actions/download-artifact@v3
        with:
          name: result.txt

      - name: Get Cypress outcome
        id: get_cypress_outcome # Per poder referenciar-ho després.
        run: echo "::set-output name=cypress_outcome::$(cat result.txt)"

      - name: Add badge to README
        uses: ./.github/actions/add-badge
        with:
          cypress_outcome: ${{ steps.get_cypress_outcome.outputs.cypress_outcome }}

  deploy_job:
    runs-on: ubuntu-latest
    needs: [linter_job, cypress_job, add_badge_job]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          
